# =============================================
# generate-photos.ps1
# Tự động quét thư mục img/ và tạo photos.js
# Cách dùng: Click chuột phải → "Run with PowerShell"
# =============================================

$imgFolder = ".\img"
$outputFile = ".\photos.js"

# Ảnh chính (man.jpg) - loại khỏi quả cầu
$excludeNames = @("man.jpg","man.jpeg","man.png","man.webp","man.JPG","man.JPEG","man.PNG")

$extensions = @("*.jpg","*.jpeg","*.png","*.webp","*.gif","*.JPG","*.JPEG","*.PNG","*.WEBP","*.GIF")

# Kiểm tra thư mục img/ có tồn tại không
if (-not (Test-Path $imgFolder)) {
    Write-Host ""
    Write-Host "  [!] Không tìm thấy thư mục '$imgFolder'" -ForegroundColor Red
    Write-Host "  Hãy tạo thư mục 'img' và đặt ảnh vào đó." -ForegroundColor Yellow
    Write-Host ""
    Read-Host "Nhấn Enter để thoát"
    exit
}

# Lấy tất cả file ảnh, loại trừ man.jpg
$imgs = @()
foreach ($ext in $extensions) {
    $found = Get-ChildItem -Path $imgFolder -Filter $ext -ErrorAction SilentlyContinue |
             Where-Object { $_.Name -notin $excludeNames }
    $imgs += $found
}

# Loại bỏ trùng lặp và sắp xếp
$imgs = $imgs | Sort-Object Name -Unique

Write-Host ""
Write-Host "  =================================" -ForegroundColor Cyan
Write-Host "   Tạo photos.js từ thư mục img/" -ForegroundColor Cyan
Write-Host "  =================================" -ForegroundColor Cyan
Write-Host ""

if ($imgs.Count -eq 0) {
    Write-Host "  [!] Không tìm thấy ảnh nào trong '$imgFolder'" -ForegroundColor Yellow
    Write-Host "  Đảm bảo file ảnh có đuôi: jpg, jpeg, png, webp, gif" -ForegroundColor Gray
    "window.PHOTOS = [];" | Out-File -FilePath $outputFile -Encoding UTF8
    Write-Host ""
    Write-Host "  Đã tạo photos.js (rỗng)" -ForegroundColor Gray
} else {
    Write-Host "  Tìm thấy $($imgs.Count) ảnh:" -ForegroundColor Green
    $imgs | ForEach-Object { Write-Host "    - $($_.Name)" -ForegroundColor Gray }
    Write-Host ""

    # Tạo mảng JS với đường dẫn img/filename
    $list = ($imgs | ForEach-Object { '"img/' + $_.Name + '"' }) -join ", "
    $content = "// Auto-generated by generate-photos.ps1 - $($imgs.Count) anh`nwindow.PHOTOS = [$list];"
    $content | Out-File -FilePath $outputFile -Encoding UTF8 -NoNewline

    Write-Host "  [OK] Đã tạo '$outputFile' thành công!" -ForegroundColor Green
    Write-Host "  [OK] $($imgs.Count) ảnh sẽ hiện trên quả cầu 3D" -ForegroundColor Green
}

Write-Host ""
Write-Host "  Lưu ý: man.jpg sẽ hiển thị ở màn hình lời chúc," -ForegroundColor Cyan
Write-Host "  các ảnh khác sẽ hiện trên quả cầu 3D." -ForegroundColor Cyan
Write-Host ""
Read-Host "  Nhấn Enter để thoát"
